config/routes.rb
Rails.application.routes.draw do
  get 'resumes/index'

  get 'resumes/new'

  get 'resumes/create'

  get 'resumes/destroy'
  resources :resumes, only: [:index, :new, :create, :destroy]   
   root "resumes#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/resume.rb
class Resume < ApplicationRecord
    mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.   
    validates :title, :category, :year, :price, :attachment, presence: true # Make sure the owner's name is present.
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController   
  def index   
     @resumes = Resume.all   
  end   
     
  def new   
     @resume = Resume.new   
  end   
     
  def create   
     @resume = Resume.new(resume_params)   
       respond_to do|format| 
     if @resume.save 
      format.html { redirect_to resumes_path, notice: 'Resume was Successfully uploaded.'}  
      format.json { render :show, status: :created, location: @resume}
         
     else   
        format.html {render :new } 
        format.json { render json: @resume.errors, status: :unprocessable_entity }
     end   
    end  
  end   
     
  def destroy   
     @resume = Resume.find(params[:id])   
     @resume.destroy   
     redirect_to resumes_path, notice:  "Successfully deleted."   
  end   
     
  private   
     def resume_params   
     params.require(:resume).permit(:title, :category, :year, :price, :attachment)   
  end   
     
end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>   
<html>   
 <head>   
      <title>File Uploading</title>   
      <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>   
      <%= javascript_include_tag "application", "data-turbolinks-track" => true %>   
      <%= csrf_meta_tags %>   
   </head>   
      
   <body>   
      <div>   
         <%= yield %>   
      </div>   
   </body>   
</html>  

app/views/resumes/create.html.erb
<h1>Resumes#create</h1>
<p>Find me in app/views/resumes/create.html.erb</p>

app/views/resumes/destroy.html.erb
<h1>Resumes#destroy</h1>
<p>Find me in app/views/resumes/destroy.html.erb</p>

app/views/resumes/index.html.erb
<center> <h1> Online Movie market store  </h1>  </center>
<style>
h1{
    color:#665743;
}
body{
    background:#F6F7BE;
}
a{
    color:green;
}
a:hover{
    color:red;
}

.card-img-top
{
   height:235px;
   width:252px;
}
footer{
    background: green;
    padding: 20px;

}
footer p{
    
    text-align: center;
    color: #fff;
}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
</style>


<center><h1>Movies </h1></center>
<div class="container">   
<% if !flash[:notice].blank? %>   
   <div>   
      <%= flash[:notice] %>   
   </div>   
<% end %>   
  
<br>   
  
<center><b><u><h4><%= link_to "New Resume", new_resume_path %></h4></u></b></center>  
<br>   
<br>   

<div class="album py-5 bg-light">
        <div class="container">
        <div class="row">
 <% @resumes.each do |resume| %> 
          
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <img src="<%= resume.attachment %>" class="card-img-top"  alt="Card image cap">
                <div class="card-body">
                  <p class="card-text"><b>Title:</b><%= resume.title %><br><b>category:</b><%= resume.category %><br><b>Year:</b><%= resume.year %><br><b>price:</b><%= resume.price %></p>
                  <b><u><%= link_to "Download", resume.attachment_url %></b></u>
                  <b><u><%= link_to "Delete",  resume, method: :delete, confirm: "Are you sure you want to delete #{resume.attachment}?" %>
                  </b></u>
                  </div>
                </div>
              </div>
              <% end %> 
            </div>
            <br>
            <br>
            <footer>
      
<p>all right reserved by uzaruharanira marc &nbsp;2019    </footer>

app/views/resumes/new.html.erb
<style>
h1{
    text-align:center;
    color:green;

}
.container{
    margin-left:45px;
    background:#F6F7BE;
    padding-top:20px;
}
label{
    color:green;
}
class{
    color:green;
}
</style>











<h1>MOVIES UPLOAD</h1>
<div class="container">
  
   <%= form_for @resume, html: { multipart: true } do |f| %>   
      <%= f.label :title %> &nbsp  &nbsp &nbsp &nbsp
       
    <%= f.text_field :title %> 
       
    <br><br>
    
       <%= f.label :category %>   
     <%= f.text_field :category %>
     <br><br>
      
      <%= f.label :year %> &nbsp  &nbsp &nbsp &nbsp
       
      <%= f.text_field :year %>
      <br><br>
       
      
    
     <%= f.label :price %>  &nbsp  &nbsp &nbsp &nbsp
        
    <%= f.text_field :price %> 
       <br><br>
        <%= f.label :attachment %> 
      <%= f.file_field :attachment %> 
      <br><br> 
      
      <%= f.submit "Save",class: "btn btn-primary" %>   
   <% end %>
   </div>